In [2]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate synthetic bank loan data for 100 customers
n_customers = 100
raw_data = {
    'Customer_ID': range(1001, 1001 + n_customers),
    'Age': np.random.randint(20, 65, size=n_customers),
    'Monthly_Income': np.random.randint(300000, 2500000, size=n_customers),
    'Loan_Amount': np.random.randint(500000, 5000000, size=n_customers),
    'Loan_Paid': np.random.choice([0, 1], size=n_customers, p=[0.3, 0.7]) # 0=No, 1=Yes
}

# Convert to DataFrame
df_original = pd.DataFrame(raw_data)

# Save original data to a CSV file (Simulation of upload)
df_original.to_csv('original_data.csv', index=False)

# Display the first 5 rows
df_original.head()

   Customer_ID  Age  Monthly_Income  Loan_Amount  Loan_Paid
0         1001   58         2037095      4524066          1
1         1002   48         2411138      4635314          0
2         1003   34          886146      1410681          0
3         1004   62         2409818      2107618          1
4         1005   27          588998      4396830          1

In [4]:
from sdv.metadata import SingleTableMetadata
from sdv.single_table import GaussianCopulaSynthesizer

# 1. Initialize and detect metadata from the original dataframe
metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data=df_original)

# Update column intent: Ensure Customer_ID is treated as an identifier, not a numeric feature
metadata.update_column(column_name='Customer_ID', sdtype='id')

# 2. Initialize the Synthesizer and train the model (The Cleanroom Engine)
synthesizer = GaussianCopulaSynthesizer(metadata)
synthesizer.fit(df_original)

# 3. Generate 50 safe, fully private synthetic records
df_synthetic = synthesizer.sample(num_rows=50)

# Save the synthetic data to a separate CSV file
df_synthetic.to_csv('synthetic_data.csv', index=False)

# Display the first 5 rows of the privacy-safe data
df_synthetic.head()

c:\Users\Anna Mmary\anaconda3\envs\cleanroom_env\lib\site-packages\sdv\single_table\base.py:178: FutureWarning: The 'SingleTableMetadata' is deprecated. Please use the new 'Metadata' class for synthesizers.
  warnings.warn(DEPRECATION_MSG, FutureWarning)
c:\Users\Anna Mmary\anaconda3\envs\cleanroom_env\lib\site-packages\sdv\single_table\base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

   Customer_ID  Age  Monthly_Income  Loan_Amount  Loan_Paid
0      9924220   53          934994      3953441          1
1     15841962   57         1480716      3274515          1
2      8619145   29         1734782       834498          1
3      3499117   54         2247852      3738338          1
4     14610977   43         1669006      4494759          1